### ISSUE TITLE
线上有两个报错，能解决下吗？

### ISSUE THREAD

**Issue by lb1207087645** [jenly1314/NeverCrash#6]
ava.lang.NullPointerException: Attempt to read from field 'android.app.Activity android.app.ActivityThread$ActivityClientRecord.activity' on a null object reference
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3695)
	at android.app.ActivityThread.access$1500(ActivityThread.java:165)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1413)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at com.king.thread.nevercrash.NeverCrash$1.run(NeverCrash.java:66)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5669)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

java.lang.IllegalArgumentException: Activity client record must not be null to execute transaction item: TopResumedActivityChangeItem{onTop=false}
	at android.app.servertransaction.ActivityTransactionItem.getActivityClientRecord(ActivityTransactionItem.java:85)
	at android.app.servertransaction.ActivityTransactionItem.getActivityClientRecord(ActivityTransactionItem.java:58)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:43)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2673)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:206)
	at android.os.Looper.loop(Looper.java:296)
	at com.king.thread.nevercrash.NeverCrash$1.run(NeverCrash.java:66)
	at android.os.Handler.handleCallback(Handler.java:955)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:206)
	at android.os.Looper.loop(Looper.java:296)
	at android.app.ActivityThread.main(ActivityThread.java:8971)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:976)

**Comment by jenly1314** [comment]
[NeverCrash](https://github.com/jenly1314/NeverCrash) 的用途是：捕获App异常，然后让你去处理，不是帮你处理异常的。
